# Stage 1
FROM node:18-alpine as build-step
RUN mkdir -p /client
WORKDIR /client
COPY package.json /client
RUN npm install -g @angular/cli
RUN npm install
COPY . /client/
# RUN npm run build
# Stage 2
FROM nginx:1.17.1-alpine
COPY --from=build-step /app/docs /usr/share/nginx/html