
# FROM node:latest as node
# WORKDIR /app
# COPY package.json /app
# RUN npm install
# COPY . /app
# CMD [ "node","server.js" ]
# Define node version
FROM node:12.16.1-alpine
# Define container directory
WORKDIR /usr/src/app
# Copy package*.json for npm install
COPY package*.json ./
# Run npm clean install, prod dependencies only
RUN npm ci --only=production
# Copy all files
COPY . .
# Expose port 4202 for server
EXPOSE 4202
# Run "node server/run.js"
CMD ["node", "server.js"]