version: '^3'
services:
  backend:
    build:       
      context: ./
      dockerfile: Dockerfile.server
    ports:
      - "4202:4202"
    container_name: backend
    image: api
    environment:
      - NODE_ENV=production
  database:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  frontend:
    build: 
      context: ./
      dockerfile: Dockerfile.ui
    ports:
      - "4200:80"
    links:
      - server
    container_name: client
    image: ui
    environment:
      - CHOKIDAR_USEPOLLING=true
      # - CI=true